language: csharp

env:
  - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis

sudo: required
dist: xenial
dotnet: 2.2.103
mono:
  - latest
os:
  - linux

branches:
  except:
    - gh-pages

script:
  - ./build.sh Test quick

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
